<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Emertac.UI.Application\Emertac.UI.Application.csproj" />
    <ProjectReference Include="..\Emertac.UI.Domain\Emertac.UI.Domain.csproj" />
  </ItemGroup>

</Project>
