<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Emertec.Application\Emertec.Application.csproj" />
    <ProjectReference Include="..\Emertec.UI.Application\Emertec.UI.Application.csproj" />
    <ProjectReference Include="..\Emertec.UI.Infrastructure\Emertec.UI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
